---
- hosts: localhost
  connection: local
  tasks:

    - ec2_metadata_facts:
      register: ec2_metadata

    - name: display metadata of Instance
      debug: msg="{{ ec2_metadata.instances | map(attribute='instance_id') | list }}"


